### ISSUE TITLE
class \MIAFirebase\Messaging not found in the project

### ISSUE THREAD

**Issue by bernard-ng** [MobileIA/mia-firebase-expressive#1]
the messaging factory should create a new instance of \MIAFirebase\Messaging which is not in the project

**Comment by matiascamiletti** [comment]
Hi, the class is in: https://github.com/MobileIA/mia-firebase-zf3

Add in your composer.json:

"repositories": [
        {
            "type": "git",
            "url": "https://github.com/MobileIA/mia-firebase-zf3.git"
        },
        {
            "type": "git",
            "url": "https://github.com/MobileIA/mia-firebase-expressive.git"
        }
    ]

**Comment by bernard-ng** [comment]
thanks
